# Setup
title:        Zhaky's pages
tagline:      just another website to share things
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Zhaky
  url:        https://zhakygng.github.io 

# Gems
plugins_dir:
  - jekyll-paginate

#Others
markdown: kramdown